### ISSUE TITLE
关于一个BUG的问题

### ISSUE THREAD

**Issue by zhenaiwork** [MCTown/DimensionalThreading#2]
https://github.com/WearBlackAllDay/DimensionalThreading/issues/68
请问这个BUG你是否有能力修复一下，真的拜托了大佬。

**Comment by CaveNightingale** [comment]
轰炸机无法使用有litemetica文件提供吗？感觉描述太简陋了

**Comment by zhenaiwork** [comment]
www.zhenai.work:8000/demo.litematic

**Comment by zhenaiwork** [comment]
http://www.zhenai.work:8000/demo.zip
